### ISSUE TITLE
getSecretThing

### ISSUE THREAD

**Issue by smoore4moma** [auth0-community/auth0-aurelia-samples#10]
getSecretThing in app.js seems to reference the server in the [Quotes sample](https://auth0.com/blog/creating-your-first-aurelia-app-from-authentication-to-calling-an-api/).  Probably should just remove the button and function in app.html/js?  Or is there a way to return the secret thing?  I have the quotes demo working but of course it uses a separate jwt.

`this.http.fetch('/api/protected-route'`

**Comment by chenkie** [comment]
If you protect the API with the signing secret used for your client then you can use the JWT you get when you log in to fetch that resource. Is that what you're after?

**Comment by smoore4moma** [comment]
Yes, you are right.  Once I did set the Auth0 Client Secret and the secret in config.js the same, and restarted the quotes server, I was able to use the code below which worked.

```
getSecretThing() {
  this.http.fetch('http://localhost:3001/api/protected/random-quote', {
  headers: {
  'Authorization': 'Bearer ' + localStorage.getItem('id_token');
  }
})
  .then(response => response.text())
  .then(response => {
    this.secretThing = response;
});
}
```
  
Thanks for your help!

**Comment by chenkie** [comment]
awesome!

**Comment by adriatic** [comment]
@smoore4moma writes:

> Yes, you are right. Once I set the Auth0 Client Secret and the secret in config.json the same, and restarted the quotes server, I was able to use the code below which worked.

I believe that this is the response to Ryan's recommendation:

> If you protect the API with the signing secret used for your client then you can use the JWT you get when you log in to fetch that resource. Is that what you're after?

Unless I am off by a lot, the sample using the **`getSecretThing`** function is Aurelia SPA - by definition not trusted, meaning that the "signing secret" should not appear anywhere.

Can you explain what am I missing. In particular, what is the precise meaning of **`If you protect the API with the signing secret used for your client`**?

**Comment by chenkie** [comment]
@adriatic, the signing secret in this case lives on the server and is used in the JWT verification middleware there. So the JWT is signed by Auth0, is saved in the Aurelia app, and then gets sent to the API where it is verified (against the secret) before the resources are released.

**Comment by chenkie** [comment]
Keep in mind that this is assuming the JWT is signed using the HS256 alg. If it's RS256 that is used instead, then the JWT needs to be verified against the JSON Web Key Set (JWKS) for the Auth0 tenant instead of the signing secret.

**Comment by adriatic** [comment]
Yes, @chenkie - I am aware of the importance of using HS256 algorithm and the reasons why it has to be used in the SPA - Resource server scenario. I am trying to understand your term **`protect the API with the signing secret used for your client`** - as from this term I am not seeing the "recipe" how to do this. 

Let me be more specific and use this image

![image](https://cloud.githubusercontent.com/assets/2712405/24335359/6dfb366c-1249-11e7-921a-d5934a530857.png)

taken from the article **[Call APIs from Client-side Web Apps](https://auth0.com/docs/api-auth/grant/implicit)** - your **[Aurelia Login sample](https://github.com/auth0-community/auth0-aurelia-samples/tree/master/01-Login)** begins to address this situation, as far as I understand it.

**Fact 1**: The Aurelia app provides the access to the Auth0 Lock component and allows the user to enter his credentials (in my case I am using UserID and Password, where the user of of course registered with Auth0)

**Fact 2**: Auth0 Lock component returns the JWT token (snippet below)

```
this.lock.on("authenticated", (authResult) => {
      self.lock.getProfile(authResult.idToken, (error, profile) => {
        if (error) {
          // Handle error
          return;
        }

        localStorage.setItem('id_token', authResult.idToken);
        localStorage.setItem('profile', JSON.stringify(profile));
        self.isAuthenticated = true;
        self.lock.hide();
      });
    });
```

### Issue:

**Why would my **Resource server** be willing to authorize my attempt to access its API endpoints?**

Note that this is the same question @smoore4moma asked **[above](https://github.com/auth0-community/auth0-aurelia-samples/issues/10#issuecomment-286938378)** 

I am repeating this question as I did not understand your response. My confusion comes mostly from the fact that @smoore4moma references your (pretty old) article **[Creating your first Aurelia app: From authentication to calling an API](https://auth0.com/blog/creating-your-first-aurelia-app-from-authentication-to-calling-an-api/)**, which in turn makes use of the Paul's "abstraction" of Auth0, which is Satellizer based and as such a wrapper on something that is far inferior to Auth0 PaaS.

Please note that I am being **very verbose** in order to prevent another miscommunication, which is mostly due to the fact that you did not complete the set of Aurelia Quick starts.

I am aware that I could likely get all of the information from **[Call APIs from Client-side Web Apps](https://auth0.com/docs/api-auth/grant/implicit)** document, but since I started with trying to provide some feedback on sample code, I decided to write all this 😄

**Comment by adriatic** [comment]
The (much shorter) way to ask the same question is 

How is the statement **`4. The app can use the access_token to call the API on behalf of the user.`** from https://auth0.com/docs/api-auth/grant/implicit implemented?

**Comment by chenkie** [comment]
@adriatic I believe the confusion lies in the the fact that we are currently migrating docs and samples to [OIDC-conformant](https://auth0.com/docs/api-auth/tutorials/adoption), in which case the `access_token` is used to make secured calls to a resource server. In the old scenario, which this sample is built around, the `id_token` is sent. Since the `id_token` is signed with the secret produced in your Auth0 dashboard, that secret can in turn be used to verify the `id_token` at your own resource server.

To answer your question about the code needed to implement this with the `access_token`, it's really just a matter of saving the `access_token` returned by Auth0 once authentication is complete and then sending that token to the resource server. There is an example of saving the `access_token` [here](https://github.com/auth0-samples/auth0-javascript-samples/blob/master/04-Calling-API/app.js#L85-L93).

The real work comes when the `access_token` is to be verified at the resource server. With OIDC-conformant, `access_token`s are signed using RS256 which means that they need to be verified using a keyset. This is done using a remote Auth0 JSON Web Key Set for your Auth0 account and an implementation in Express can be found [here](https://github.com/auth0-samples/auth0-express-api-samples/blob/master/01-Authenticate-RS256/server.js).

Hopefully that clarifies things. We are currently on the migration path and the Aurelia sample (along with a few others) are still in need of an update.

**Comment by adriatic** [comment]
No, we are still ways apart, @chenkie, unfortunately. My question is a lot simpler than what you think and it really bugs me that I cannot explain what I need. Here is my next attempt, using the same code snippet:
```
this.lock.on("authenticated", (authResult) => {
      self.lock.getProfile(authResult.idToken, (error, profile) => {
        if (error) {
          // Handle error
          return;
        }

        localStorage.setItem('id_token', authResult.idToken);
        localStorage.setItem('profile', JSON.stringify(profile));
        self.isAuthenticated = true;
        self.lock.hide();
      });
    });
```
Once the above code is executed, the (human) user, has the access to JWT token stored in the variable **`authResult.idToken`**.

**Question**: as this token was received without any specification where will it be used, how can it be used to gain authorized access the resource server. The token should be used for a specific task - and I do not see where is this task specified, before asking for the token, because there is no single example that illustrates the flow which includes all participants: client (SPA), server (resource server) and Auth0 being "proxied" by Auth0 Lock.

**Comment by chenkie** [comment]
If I'm understanding correctly, the confusion is likely still a result of the legacy vs OIDC-conformant Auth0 flows. In the legacy setup, you can have a "client" in the Auth0 dashboard which is meant to represent your Aurelia (or any other SPA/mobile/round-trip) app. In this setup, there isn't any specification of a resource server for your client application, but since your client will be receiving a JWT `id_token`, it can be used to access your resource server. All that's needed is for you to protect your resource server endpoints with the signing secret for the JWT. Again, there's no specification of which resource server your token will be used for when you start the authentication process.

Aligning fully with OIDC in the OIDC-conformant flow (which this sample has yet to be updated for), the resource server is considered in this relationship and is a distinct entity in Auth0. The resource server for your client app can be configured in the APIs section of the Auth0 dashboard. In this scenario, you need to specify an `audience` when you initiate an authentication transaction with Auth0. The `audience` maps to an identifier that you specify for your resource server.

So to answer your question: under legacy Auth0 (which this sample uses), the resource server isn't specified. The fact that the `id_token` can be used at your resource server is simply because it can be verified against the signing secret for the token there, giving you a way to accept or reject calls for protected resources. However, under OIDC-conformant Auth0, the resource server is specified using the `audience`. An example of how to set this audience in Auth0Lock is found [here](https://github.com/auth0-samples/auth0-javascript-samples/blob/master/04-Calling-API/app.js#L17).

Have a look at the [API Tokens section](https://auth0.com/docs/api-auth/tutorials/adoption/api-tokens) of the OIDC-conformant adoption guide for more.

**Comment by adriatic** [comment]
Now, we are getting very close - thank you for your patience, so let's converge to the solution that will allow me to create a working prototype of a full stack sample. 

### Let's limit to the legacy flow (will handle the OIDC case later)
My case is described in **[SPA + API](https://auth0.com/docs/architecture-scenarios/application/spa-api)** document. Is this true? 

### Step 2
Since there is no resource server sample available, I was asking for the actual code that **`verifies the token received from SPA`**. Can you either write this code for me, or point me to a similar sample from a non-Aurelia SPA collection that is more complete?

**Comment by adriatic** [comment]
### Yeah
I believe that you provided the answer by pointing to **[auth0-javascript-samples](https://github.com/auth0-samples/auth0-javascript-samples)** - as this is likely the closest environment to Aurelia SPA case.

**Comment by chenkie** [comment]
No problem

Your case is described in that doc yes :)

Here's the resource server example (linked above): https://github.com/auth0-samples/auth0-express-api-samples/blob/master/01-Authenticate-RS256/server.js

The OIDC conformant example will look largely the same except for these three key things:

* the `oidcConformant` option needs to be set to `true`
* an `audience` needs to be specified
* the `access_token` needs to be saved and used at the resource server

**Comment by adriatic** [comment]
### Sigh  (sign of relief) 😏 

Once I create my **initial sample** (Aurelia SPA, Auth0 Lock, dotnet core API service) which is a part of my **[Carmel](https://github.com/aurelia-ui-toolkits/carmel-api/tree/master/dotnet)** editor for Aurelia KendoUI samples catalog, I will start writing the Auth0 samples. 

I will use this **initial sample** as the basis for our future discussion on Auth0 Aurelia samples collection.

**Comment by chenkie** [comment]
sounds good, you can check out an RS256 .NET Core sample here: https://github.com/auth0-samples/auth0-aspnetcore-webapi-sample/tree/master/01-Authentication

**Comment by smoore4moma** [comment]
And I am extremely thankful @adriatic because that is my exact scenario - Aurelia SPA with Auth0 and WebApi. This has been a very helpful thread to follow.  Thank you too @chenkie!

**Comment by chenkie** [comment]
np :)

**Comment by adriatic** [comment]
@smoore4moma I hope there was not too much "drama" in this thread; you could see how difficult it might be to find a "meeting" point when two sides do not have identical grasp of the subject being discussed (in this case, I am the trouble maker, trying to discuss something that was only partially understood.

Live and learn 😄

**Comment by smoore4moma** [comment]
This thread would make a great blog post.  I spend countless hours tracking down discussions like this, and the solution is buried somewhere in the thread.  I don't love how the Aurelia documentation has become so fragmented.  For example, validation, then validationjs, then back to validation, but it's different this time.   I do however expect Hello World examples to work without a lot of effort.   It is underestimated in terms of developer acceptance.  Off soapbox now.

**Comment by adriatic** [comment]
Preaching to the choir, Steve. My "presence" in this Auth0 domain is driven by making both Aurelia and Auth0 users happy, once I observed how incredibly difficult is to put together a full stack app - and gets even worse to include authentication and authorization in such project. 

Ryan and I are planning to improve this situation a lot - so rather than just converting this discussion to a blog (which we might do, more likely on the Aurelia side, to not disrupt the plans how to do it here),  you will soon see a discussion on how to improve the Auth0 side beyond what it has today.
